[package]
name = "czaa"
version = "0.1.0"
authors = ["RÃ¼diger Klaehn <rklaehn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zstd = "0.5.1+zstd.1.4.4"
serde_cbor = "0.11.1"
serde = { version = "1.0.106", features = ["derive"] }
salsa20 = "0.4.1"
stream-cipher = "0.3.2"
derive_more = "0.99.5"
cid = "0.5.0"
futures = "0.3.5"
multihash = "0.11.1"
tokio = { version = "0.2.20", features = ["full"] }
tracing = "0.1.13"
parking_lot = "0.10.2"
lru = "0.4.3"
hex = "0.4.2"

[dev-dependencies]
quickcheck = "0.9.2"
hex = "0.4.2"
